runtime: python312
instance_class: F1

env_variables:
  SECRET_KEY=django-insecure--oz9)bm$w61wlo(&du8v$c%3bg!(3ti!qnyvq0h2g++%!e+m0s
  DEBUG=True
  LOCAL_BUILD=True

  DEFAULT_HOST=127.0.0.1:8000
  FE_HOST=http://localhost:3000

  CORS_ALLOW_ALL_ORIGINS=True
  CORS_ALLOW_CREDENTIALS=True
  CORS_ALLOWED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000,http://localhost:5000

  ALLOWED_HOSTS=localhost,127.0.0.1,https://prestige-auto.onrender.com

  DB_ENGINE=django.db.backends.postgresql_psycopg2
  DB_HOST=aws-0-ap-southeast-1.pooler.supabase.com
  DB_PORT=5432
  DB_USER=postgres.cloixrbaywtpgzmkfavg
  DB_PASSWORD=Hoangdanh@165
  DB_NAME=prestige_auto_db

  SUPABASE_URL=https://cloixrbaywtpgzmkfavg.supabase.co
  SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsb2l4cmJheXd0cGd6bWtmYXZnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MzU5OTE3MywiZXhwIjoyMDU5MTc1MTczfQ.6W0hbMRrBNoupbqRmFvAxW7Way2g4mkBrDgCtO5abAo

  EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
  EMAIL_HOST=smtp.gmail.com
  EMAIL_PORT=587
  EMAIL_HOST_USER='hoangdanh.165@gmail.com'
  EMAIL_HOST_PASSWORD='hamgpisfdnglvvzz'
  DEFAULT_FROM_EMAIL='hoangdanh.165@gmail.com'

  TWILIO_ACCOUNT_SID=ACbd0c1ecf7a0e9dfb4123ced538b4cc67
  TWILIO_AUTH_TOKEN=8f478f6a1ddde6b09adb5104223f6d06
  TWILIO_PHONE_NUMBER=+13363449249

  SINCH_KEY_ID=9fad7e02-a53b-4ed8-bd82-6b4b3b9f4007
  SINCH_KEY_SECRET=XxZe51dkcE+owqYcC1N2GQ==
  SINCH_PHONE_NUMBER=+447520651428
  SINCH_SMS_URL=https://us.sms.api.sinch.com/xms/v1/9fad7e02-a53b-4ed8-bd82-6b4b3b9f4007/batches


  AWS_ACCESS_KEY_ID=AKIA5G2VGWDFVELDLEXR
  AWS_SECRET_ACCESS_KEY=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
  AWS_STORAGE_BUCKET_NAME=prestige-auto-bucket
  AWS_S3_SIGNATURE_NAME=s3v4,
  AWS_S3_REGION_NAME=ap-southeast-1
  AWS_S3_FILE_OVERWRITE=False
  AWS_DEFAULT_ACL=None
  AWS_S3_VERIFY=True
  DEFAULT_FILE_STORAGE=storages.backends.s3boto3.S3Boto3Storage
  MEDIA_URL=https://prestige_auto_bucket.s3.ap-southeast-1.amazonaws.com/

  ACCESS_TOKEN_LIFETIME=10
  REFRESH_TOKEN_LIFETIME=1
  ROTATE_REFRESH_TOKENS=False
  BLACKLIST_AFTER_ROTATION=True
  ALGORITHM=HS256
  SIGNING_KEY=django-insecure-ct1+c+q2(5!2@st^#y-avaw7dr(&^a%)dh!!^(h1o3v7(^*99r
  AUTH_HEADER_TYPES=Bearer


  CLIENT_ID=1071523760815-oc43l3285279jcco8v4gqminqrk2kdo8.apps.googleusercontent.com

  GEMINI_API_KEY=AIzaSyAJchPtrm0fZ3IDqYvJOvtmsAjMYk-FEBY
  GEMINI_MODEL=gemini-2.0-flash-thinking-exp-01-21
  GEMINI_EMBEDDING_MODEL=embedding-001

  REDIS_INTERNAL_URL=redis://red-cvdveqfnoe9s73ej7u7g:6379
  REDIS_EXTERNAL_URL=rediss://red-cvdveqfnoe9s73ej7u7g:w5gEVih41Nydneiut03nHJPVgOhqRgkn@singapore-keyvalue.render.com:6379

  GS_CREDENTIALS_BASE64=ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAic3RhdGVseS13aW50ZXItNDU1NjE0LW0zIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiZjc4MTNiNGYwODJlMDk0NjgxNTBlZGU3MDM0Y2Q0YjZhNGVkMTFiZiIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZBSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS1l3Z2dTaUFnRUFBb0lCQVFEbG42enZOaHk4UndFNlxuNFRWellURTl4djZoU3BQVGRtdE9VVGVOWmxJZFN6V1pIYktRbHUrSmdRUnVOd3JyeU41QzN4a3pKd0tIZi9xOVxuTUxrbTU5U3EyYzdtZWpDdlJLZitVVDFHU2pybDIrRnFrUEx6OUVRR0tQRllsSC9Kekd4bk5OL2ZBT1NXL3ZlQVxuRERId2xRKzZmajBXYlA1emZpK2hFRmM3OFd1RkNPSVpQcEE1Rk54dFBWY0g5U2toMmY1WVBBYUt6MTJjZkdTT1xuWGRCNlkwTDBDQnZ4TXJSbFQyT2p0bFNZVkxyQlFUb3VsdVhKSHpITzE1ZFMwWEpRSDI5cHAwNWRlVEozZFZSZlxucjZVU0dLTFNrVGFrT051VlZXUWxVWG1XZlc3bGxNSHFWZlhGaDgrcWtsSmdDMTZnV2xTbXlVYW5meituSTVIbVxuSVRLYTZVK2RBZ01CQUFFQ2dnRUFBcDg0ZUtGejRlRW5BM0Z2akhvUFRPR2VlMkJWb0hRdXROTTZsaWtWUmtrRlxuNWZ5djB2VFdRVjljR2V5K1R0anVxTWJSWVMzUWhUN25NYmZYdFdPdm9FL05EQUZZZ3ZmVUR6OEZrRzJTajBOYlxuMGVnR2VOWDdoNGZQZkZwekVjUFN6UTdqMWpFS3dILzRKWVIrSVgxM2s0S1RnZjVoU0Jlb2NEeTJoNThIRjVyRlxuS0FLU3V6YjRhZysvN3gxbUpIdFR4cE1JRit0WHYxWk9IWHVwMFJibmREbzFvTDhTUFNLbWxpem5lSHRUZ0tmclxuZkVaMkloc2svc0NtdVRtSU5SQ3NEN2NrcnN1UmF4VEQwaFNPTEJxWGkzQmJVdzJPNzRENjRldHZXOW9aTDJsSVxuODNCbzk0aEtsUjRUTGE5RDRSSk5SSGpESmRqQVk5dkR2L2tvRG1aTUJRS0JnUUQ2RU1nR0JaRjV1TVR5eGM1eVxuOGl5U3E2MlFzUU5WU0tNYXpQWFJvZHlsSHhOSHFVN0FyVFU0VGdrTW1SQ1I0NktTTmVaMHcrNnRicXRSNXI4eVxuTC9wM2JFQy9KUkducStIa0N6U1I1MndzK3lyUy85UG1NZGZRaHhMdGV6Tzk5eWtlMHYzZmVSUmdtZ2ZMOWRLelxuaW5Nc3YwazgvaHNrQzNIcWhVNld5ajVuU3dLQmdRRHJFclJSdHQxN3FyaTA3TDN4YU1Lb0I3dTYrRytxMFVQZFxuMXlYZWJuVlRjRVNXSmlCSGswN1ZMOFBBbjhjU29yL0tkTVgzdVpzYUJSR25NSFdtNURTTU5qdHUrSFlRckg4c1xud3pEQkVSanBBSmxUL21lekFFL3lMeTd4bkRiNk1XeUtHVVh1YUV6YUhUT2xaazU3d3ZDN2ljR2ZMU0dwSStpRlxuMUNQbkhRL0x0d0tCZ0NWUUtiaVVUaCsralV5NGJWVERoQmtpbXRSelJVOE5kcUVDSWsvMGVncjlkeEFEV0dmeFxuc0haRlZwNVZuSjVZUENMYS9oZEFRVFlKeEhDRklOUnBTbE5WaU5lOHZVU3FwaHN6L05Va2xnU2tPY0NnUWNzZ1xuZHRaN3dUeEVYUFVra3pNeFFvWjg5Nmh1YzJsZ3RkN3Fjc01qaTljWkI0MjZVM1l1REFyK0JJKy9Bb0dBSEFWS1xud1VMTysrTEp5YWMrclB3VDEvdTBBUUdFTGhScnhwSFN6Y1RVNzNFK2U3ZG51YUJ4a1MvMFlZMnFLU3FGT2hqWlxuVUVJcm50cGoxRTRPZUNwVHFUTDl1cWliU2ptRm4weFZEMjUrVGFmb252NkFWZkgvbFpyU09iS3BTd0dCTXFUNFxubFFhUndwNGdmZUxJRURDWWlZSk9OaThuQ0FaanZUQWdaM2dyWGRrQ2dZQXcwTmxUbms2bmhxN2ZwOVFrd3MyeFxuNnhlclB4OFRNMUFlZXNzU1RWazRsUStsSmZnOElXVUV2MU95T2FweG4rZmlyNVhQMkFFY0RqM0NJQ0txYU1YMFxuTzJjNHFVU3FBWW1tOTF0MWVrSXArU2w4OFhUQkNFZ0ZSVmlsQjJGSzEva1FLYUdDcnZ4UkpMR0V3Zy9FaGd4ZVxuemZqQkNYVVRHTkRVaCtoajBsa2lqZz09XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAicGEtc2EtMTEyQHN0YXRlbHktd2ludGVyLTQ1NTYxNC1tMy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMTQyMzA4MzI1ODgyOTAzNTExNDIiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L3BhLXNhLTExMiU0MHN0YXRlbHktd2ludGVyLTQ1NTYxNC1tMy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgInVuaXZlcnNlX2RvbWFpbiI6ICJnb29nbGVhcGlzLmNvbSIKfQo=

handlers:
- url: /.*
  script: auto

entrypoint: gunicorn --timeout 90 backend.wsgi:application