# Generated by Django 5.1.7 on 2025-05-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='qr_code_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
