# Generated by Django 5.1.7 on 2025-05-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_payment_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('momo', 'MoMo'), ('zalo_pay', 'ZaloPay'), ('vn_pay', 'VNPay'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
