# Generated by Django 5.1.7 on 2025-04-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatbothistory',
            table='chatbot_history',
        ),
    ]
