# Generated by Django 5.1.7 on 2025-04-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatbothistory_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbothistory',
            name='response',
        ),
        migrations.AddField(
            model_name='chatbothistory',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
