# Generated by Django 5.1.7 on 2025-04-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_chatbothistory_response_chatbothistory_is_bot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbothistory',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
