# Generated by Django 5.1.7 on 2025-03-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_last_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_message_seen',
            field=models.BooleanField(default=False),
        ),
    ]
