# Generated by Django 5.1.7 on 2025-04-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_appointmentservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
