# Generated by Django 5.1.7 on 2025-04-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_appointment_table_alter_service_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
