# Generated by Django 5.1.7 on 2025-04-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_service_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='duration',
            new_name='estimated_duration',
        ),
    ]
