# Generated by Django 5.1.7 on 2025-04-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rename_duration_service_estimated_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='additional_customer_information',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='estimated_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vehicle_information',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
