# Generated by Django 5.1.7 on 2025-04-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_appointment_additional_customer_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
