# Generated by Django 5.1.7 on 2025-04-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_appointment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='discount_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='discount_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
