# Generated by Django 5.1.7 on 2025-04-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='estimated_end_time',
            new_name='vehicle_ready_time',
        ),
    ]
