# Generated by Django 5.1.7 on 2025-04-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_rename_estimated_end_time_appointment_vehicle_ready_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
