# Generated by Django 5.1.7 on 2025-04-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_appointment_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
