# Generated by Django 5.1.7 on 2025-04-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_alter_service_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
