# Generated by Django 5.1.7 on 2025-04-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_appointment_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminded_before_1d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminded_before_1h',
            field=models.BooleanField(default=False),
        ),
    ]
