# Generated by Django 5.1.7 on 2025-04-25 05:52

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_serviceembeddings'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
