# Generated by Django 5.1.7 on 2025-05-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_service_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
