# Generated by Django 5.1.7 on 2025-05-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_appointmentservice_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminded_vehicle_ready',
            field=models.BooleanField(default=False),
        ),
    ]
