# Generated by Django 5.1.7 on 2025-05-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_appointment_reminded_vehicle_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('processing', 'Processing')], default='pending', max_length=10),
        ),
    ]
