# Generated by Django 5.1.7 on 2025-05-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='invoice_created',
            field=models.BooleanField(default=False),
        ),
    ]
