service_samples = [
    "Can you tell me what services your garage offers?",
    "Do you provide car maintenance services?",
    "What type of repairs can you handle?",
    "I need an oil change, do you do that?",
    "Is tire rotation available at your garage?",
    "Can you inspect my brakes?",
    "Do you do engine tuning?",
    "How much is a car wash?",
    "Can I book a detailing service?",
    "Do you offer ceramic coating for cars?",
    "Is air conditioning service available?",
    "Can you replace my battery?",
    "Do you install dashcams?",
    "I'm interested in window tinting, can you help?",
    "Do you offer sound system upgrades?",
    "Can you replace my timing belt?",
    "Do you do general vehicle inspection?",
    "What’s included in a pre-purchase inspection?",
    "How long does it take to flush fluids?",
    "Do you handle transmission repairs?",
    "Can I get my suspension fixed here?",
    "Do you offer LED headlight upgrades?",
    "Can I get a wheel alignment today?",
    "Is there any roadside assistance service?",
    "Do you offer pickup and delivery for vehicles?",
    "Can you renew my registration for me?",
    "I want to upgrade the body kit. Do you do that?",
    "What kind of car care services do you provide?",
    "Can I schedule multiple services at once?",
    "Do you offer appointment bookings online?",
    "Can I speak to someone about customizing my car?",
    "What’s the price range for your upgrade services?",
    "How long does a full detailing service take?",
    "Do you have service packages?",
    "Can I get a quote for multiple services?",
    "Do you work with specific car brands?",
    "Is ceramic coating worth it for my car?",
    "Can I drop my car off and pick it up later?",
    "Do you send reminders for regular maintenance?",
]


all_service_samples = [
    "What are all the services your garage provides?",
    "Can you give me an overview of the services you offer?",
    "What types of services are available at your garage?",
    "Do you have a full list of services you perform?",
    "What kind of automotive services do you specialize in?",
    "Can you tell me about the range of services you provide?",
    "What’s the complete menu of services at your garage?",
    "Do you offer a comprehensive set of car care services?",
    "What services can I get done at your garage?",
    "Can you provide details on all the automotive services you have?",
    "What are the main services your garage is known for?",
    "Do you have a catalog of all your vehicle services?",
    "What’s included in your full range of garage services?",
    "Can you list all the maintenance and repair services you offer?",
    "What types of car-related services do you handle?",
    "Do you provide both repair and upgrade services?",
    "Can I get a breakdown of all the services you do?",
    "What’s the scope of services available at your garage?",
    "Do you offer everything from maintenance to customization?",
    "Can you tell me about every service you provide for vehicles?",
    "What are the different categories of services you offer?",
    "Do you have a complete service package for cars?",
    "Can you explain all the things you can do for my vehicle?",
    "What’s the full spectrum of services at your garage?",
    "Do you cover all aspects of car maintenance and repair?",
    "Can I get a summary of all your garage’s offerings?",
    "What services do you provide for both new and old cars?",
    "Do you offer a wide variety of automotive services?",
    "Can you tell me everything your garage can do for my car?",
    "What are all the options for vehicle care at your garage?",
    "Do you provide a full suite of auto repair and maintenance services?",
    "Can you give me a rundown of all your service offerings?",
    "What’s the complete list of things you can do for my vehicle?",
    "Do you handle all types of automotive needs?",
    "Can you provide a detailed list of every service you offer?",
    "What services are available for someone looking to maintain their car?",
    "Do you have a one-stop garage for all car-related services?",
    "Can you tell me about the full range of your garage’s capabilities?",
    "What are all the ways you can help with my car’s needs?",
    "Do you offer a complete set of solutions for vehicle maintenance?",
]

chitchat_samples = [
    "How's the weather today?",
    "Who is the President of the United States?",
    "What time is it in Tokyo right now?",
    "Can you tell me a joke?",
    "What’s your favorite movie?",
    "Do you believe in aliens?",
    "How far is the moon from Earth?",
    "Who won the last World Cup?",
    "Tell me something interesting.",
    "What's the capital of France?",
    "How do I cook spaghetti?",
    "What’s your opinion on pineapple on pizza?",
    "Who’s the richest person in the world?",
    "Can you sing a song?",
    "What’s trending on social media today?",
    "Tell me a fun fact about animals.",
    "What should I watch on Netflix?",
    "Can you write me a poem?",
    "How do you say hello in Japanese?",
    "What's the best way to learn a new language?",
    "What’s your favorite color?",
    "Do you dream when you sleep?",
    "How old are you?",
    "What’s the meaning of life?",
    "Do you like cats or dogs?",
    "How do airplanes stay in the air?",
    "What happens if I fall into a black hole?",
    "Can you tell me my horoscope?",
    "What’s your favorite food?",
    "Do you believe in ghosts?",
]
