service_samples = [
    "Can you tell me what services your garage offers?",
    "Do you provide car maintenance services?",
    "What type of repairs can you handle?",
    "I need an oil change, do you do that?",
    "Is tire rotation available at your shop?",
    "Can you inspect my brakes?",
    "Do you do engine tuning?",
    "How much is a car wash?",
    "Can I book a detailing service?",
    "Do you offer ceramic coating for cars?",
    "Is air conditioning service available?",
    "Can you replace my battery?",
    "Do you install dashcams?",
    "I'm interested in window tinting, can you help?",
    "Do you offer sound system upgrades?",
    "Can you replace my timing belt?",
    "Do you do general vehicle inspection?",
    "What’s included in a pre-purchase inspection?",
    "How long does it take to flush fluids?",
    "Do you handle transmission repairs?",
    "Can I get my suspension fixed here?",
    "Do you offer LED headlight upgrades?",
    "Can I get a wheel alignment today?",
    "Is there any roadside assistance service?",
    "Do you offer pickup and delivery for vehicles?",
    "Can you renew my registration for me?",
    "I want to upgrade the body kit. Do you do that?",
    "What kind of car care services do you provide?",
    "Can I schedule multiple services at once?",
    "Do you offer appointment bookings online?",
    "Can I speak to someone about customizing my car?",
    "What’s the price range for your upgrade services?",
    "How long does a full detailing service take?",
    "Do you have service packages?",
    "Can I get a quote for multiple services?",
    "Do you work with specific car brands?",
    "Is ceramic coating worth it for my car?",
    "Can I drop my car off and pick it up later?",
    "Do you send reminders for regular maintenance?",
]
