# Generated by Django 5.1.7 on 2025-04-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_avatar_url_user_google_id_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Banned')], default=1),
        ),
    ]
