# Generated by Django 5.1.7 on 2025-04-17 07:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.PositiveIntegerField()),
                ('engine_type', models.CharField(max_length=255)),
                ('current_odometer', models.PositiveIntegerField(help_text='Distance traveled in kilometers')),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_province', models.CharField(max_length=255)),
                ('vin', models.CharField(blank=True, max_length=100, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'car',
                'ordering': ['-create_at'],
            },
        ),
    ]
